config/routes.rb
Rails.application.routes.draw do
  resources :event_users
  resources :location_types
  resources :locations, except: [:destroy]
  resources :events, except: [:destroy]
  resources :reviews, except: [:show]
  resources :users, except: [:index]
  get '/login', to: "sessions#new", as: 'login'
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/', to: "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :locations, through: :reviews
  has_many :event_users
  has_many :events, through: :event_users
  has_secure_password
  validates :username, uniqueness: true

  def self.search(search)
    where("name LIKE ? OR username LIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorized, only: [:new, :create]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if !!params[:search]
      @users = User.search(params[:search])
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id]=@user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    set_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to logout_path	, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :name, :age)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h4>Editing User</h4>

<%= render 'form', user: @user %>

<%= link_to 'Back', @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h4>New User</h4>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
  <div class="row">
    <div class="col s4 left">
      <h5><%= @user.name %></h5>
<p>
  <p1>Username:</p1>
  <%= @user.username %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>


<div width="225" style="width: 225px"><%= form_tag(user_path, method: "get", id: "search-form") do %>
 <%= text_field_tag :search, params[:search], placeholder: "Search for user or username" %>
  <%= submit_tag "Search", :name => nil %>
 <% end %></div>

 <% if @users.blank? && params[:search] %>
   <h6>There are no results for <%= params[:search] %>.</h6>
   <% elsif params[:search] == nil %>
    <%= "" %>
   <% else %>
   <h6>Results:</h6>
 <% end %>

<% if !!@users %>
<ul>
  <% @users.each do |user| %>
  <li><%= link_to user.name, user %></li>
  <% end %>
<% end %>
</ul>


<br><br><br>
<%= link_to 'Back', users_path %> |

<% if @user.id == current_user.id %>
  <%= link_to 'Edit', edit_user_path(@user) %><br><br>
  <%= link_to 'Log Out', logout_path %>
  <% end %>
</div>


<p>
  <ul>
<div class="col s4 ">
  <h5>Reviews:</h5>
  <% @user.reviews.each do |review| %>
    <li><%=link_to review.location.name, location_path(review.location) %></li>
    <li>Rating: <%= review.rating %></li>
    <li><%= review.content %></li><br>

    <% if @user.id == current_user.id %>
      <%= button_to "Edit Review", edit_review_path(review), :method => :get, params: {location_id: review.location.id}%><br>
    <% end %>
  <% end %>
</p>
</div>

<div class="col s4 right">
  <h5>Events:</h5>
  <ul>
<p vlink="blue">
  <% @user.events.each do |event| %>
    <% if DateTime.now < event.end_date %>
    <li><h6><%= link_to event.title, event %></h6></li>
    <li><%=link_to event.location.name, location_path(event.location) %></li>
    <li><%=event.format_date(event.start_date) + " - " + event.format_date(event.end_date)  %></li>
    <li><%= event.description.truncate(200, separator: ' ') %></li> <br>

  <% if @user.id == current_user.id %>
  <%= button_to 'Delete this Event', event_user_path(event.find_event_user(session[:user_id], event)), method: :delete, params: {event_id: event.id, user_id: session[:user_id]}, data: { confirm: 'Are you sure?' } %><br>
  <% end %>
  <% end %>
  <% end %>
  </p>
</ul>

  </p>
  <p>
  <h5>Past Events:</h5>
  <ul>

  <% @user.events.each do |event| %>
  <% if event.end_date < DateTime.now %>
  <li><h6><%= link_to event.title, event %></h6></li>
  <li><%=link_to event.location.name, location_path(event.location) %></li>
  <li><%=event.format_date(event.start_date) + " - " + event.format_date(event.end_date)  %></li>
  <li><%= event.description.truncate(200, separator: ' ') %></li> <br>
  <% if @user.id == current_user.id %>
  <%= button_to 'Delete this Event', event_user_path(event.find_event_user(session[:user_id], event)), method: :delete, params: {event_id: event.id, user_id: session[:user_id]}, data: { confirm: 'Are you sure?' } %>
</ul>

  <% end %>
  <% end %>
  <% end %>
  </div>
  </div>



<% if @user.id == current_user.id %>

  <%= button_to 'Delete this Account', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>