config/routes.rb
Rails.application.routes.draw do
  resources :event_users
  resources :location_types
  resources :locations, except: [:destroy]
  resources :events, except: [:destroy]
  resources :reviews, except: [:show]
  resources :users, except: [:index]
  get '/login', to: "sessions#new", as: 'login'
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/', to: "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location
  has_many :event_users
  has_many :users, through: :event_users

  def days_left
    (self.end_date.to_date - DateTime.now.to_date).to_i
  end

  def format_date(date)
    date.strftime("%A, %B %d, %Y")
  end

  def find_event_user(user_id, event)
    EventUser.all.find_by(user_id: user_id, event_id: event.id)
  end

  def self.search(search)
    where("location_id LIKE ?", "%#{search}%")
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    if params[:location]
      @events = Event.search(params[:location][:id])
    else
    @events = Event.all
  end
end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :title, :description, :location)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col s6">
<h5>Current Exhibitions</h5>
</div>

  <div class="col s4 right" width="200" style="width: 200px">
<div width="200" style="width: 200px">
<%= form_tag(events_path, method: "get", id: "search-form") do %>
  <%= collection_select( :location, :id, Location.all, :id, :name, {prompt: "Search by Location"}, {:class=>'browser-default'}) %>
  <%= submit_tag "Submit" %>
<% end %>
</div>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%sorted_events= @events.sort_by {|event|event.end_date}%>
    <%sorted_events.each do |event| %>
    <% if event.start_date < DateTime.now && DateTime.now < event.end_date %>
      <tr>
        <td><%= link_to event.title, event %></td>
        <td><%= event.format_date(event.start_date) %></td>
        <td><%= event.format_date(event.end_date) %></td>
        <td><%= link_to event.location.name, location_path(event.location) %></td>
      </tr>
    <% end %>
    <%@events.sort_by {|event|event.end_date.to_r}%>
    <% end %>

  </tbody>
</table>


<h5>Upcoming</h5>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%sorted_events= @events.sort_by {|event|event.end_date}%>
    <%sorted_events.each do |event| %>
    <% if DateTime.now < event.start_date  %>
      <tr>
        <td><%= link_to event.title, event %></td>
        <td><%= event.format_date(event.start_date) %></td>
        <td><%= event.format_date(event.end_date) %></td>
        <td><%= link_to event.location.name, location_path(event.location) %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<h5>Past</h5>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Location</th>
        <th colspan="3"></th>
      </tr>

    </thead>
    <tbody>
    <%sorted_events= @events.sort_by {|event|event.start_date}.reverse%>
    <%sorted_events.each do |event| %>
    <% if event.end_date < DateTime.now %>
      <tr>
        <td><%= link_to event.title, event %></td>
        <td><%= event.format_date(event.start_date) %></td>
        <td><%= event.format_date(event.end_date) %></td>
        <td><%= link_to event.location.name, location_path(event.location) %></td>
      </tr>
    <% end %>
    <% end %>

  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col s6 left">
<h5>
  <%= @event.title %>
</h5>

<p>
  <%= @event.format_date(@event.start_date) %> -   <%= @event.format_date(@event.end_date) %>

</p>
<p>
  <% if DateTime.now < @event.end_date  %>
  <%= @event.days_left %> days left on view
  <% end %>
</p>
<p>
  <strong>Location:</strong>
  <%=link_to @event.location.name, location_path(@event.location) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>
</div>
<div class="col s3 right">
<h5>Attendees:</h5>
<ul>
<% @event.event_users.each do |event_user| %>
<li><%=link_to event_user.user.name, user_path(event_user.user)%></li>
<% end %>
</ul>
<%= button_to "Add Event to Profile", event_users_path, action: "create",
params: {event_id: @event.id, user_id: session[:user_id]}
 %><br>
</div>
 </div>

<!--Fix button above to take in current_user instance -->

<%= link_to 'Back', events_path %>