config/routes.rb
Rails.application.routes.draw do
  resources :event_users
  resources :location_types
  resources :locations, except: [:destroy]
  resources :events, except: [:destroy]
  resources :reviews, except: [:show]
  resources :users, except: [:index]
  get '/login', to: "sessions#new", as: 'login'
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/', to: "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :location_type
  has_many :reviews
  has_many :users, through: :reviews
  has_many :events
  attr_writer :overall_rating


  def overall_rating
    ratings = []
    self.reviews.map do |review|
      ratings << review.rating
    end
    ovr = ratings.inject(0, :+).to_f/ratings.count.to_f
    ovr = ovr.to_s
    if ovr == "NaN"
      ovr = "Not Rated"
    else
      ovr.to_f.round(2).to_s
    end
  end

  def self.sort_locations(params)
    # byebug
    @locations = Location.all
    if !!params[:search]
      @locations = Location.search(params[:search])
    elsif params[:option] == "neighborhood"
      @locations = Location.all.sort_by {|location| location.neighborhood}
    elsif params[:option] == "rating"
      @locations = Location.all.sort_by do |location|
        if location.overall_rating == "Not Rated"
          location.overall_rating= "0"
        else
        location.overall_rating
      end #end of do block
        end.reverse #end of if block
    elsif params[:option] == "category"
        @locations = Location.all.sort_by {|location| location.location_type.category}
    else
      @locations = Location.all
    end
  end

  def self.search(search)
    where("name LIKE ? OR neighborhood LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  def stars
    arr = []
    if self.overall_rating != "Not Rated"
      self.overall_rating.to_i.times do
        arr << "⭐️"
      end
      arr.join
    else
      ""
    end
  end


end

app/models/location_type.rb
class LocationType < ApplicationRecord
  has_many :locations
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.sort_locations(params)
    # if params[:search]
    #   @locations = Location.search(params[:search])
    # elsif params[:option] == "neighborhood"
    #   @locations = Location.all.sort_by {|location| location.neighborhood}
    # elsif params[:option] == "rating"
    #   @locations = Location.all.sort_by do |location|
    #     if location.overall_rating == "Not Rated"
    #       location.overall_rating= "0"
    #     else
    #     location.overall_rating
    #   end #end of do block
    #     end.reverse #end of if block
    # elsif params[:option] == "category"
    #     @locations = Location.all.sort_by {|location| location.location_type.category}
    # else
    #   @locations = Location.all
    # end
end


# if params[:option] == "DESC"
#   @dogs = Dog.all.sort_by {|dog| dog.employee_count}
# elsif params[:option] == "ASC"
#   @dogs = Dog.all.sort_by {|dog| dog.employee_count}.reverse
# else
#   @dogs = Dog.all
# end
# end




  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :neighborhood, :size, :cost_of_admission, :image_url, :description, :search)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :neighborhood %>
    <%= form.text_field :neighborhood %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>
<% if @locations.blank? %>
  <h4>There are no results for <%= params[:search] %>.</h4>
<% end %>

<div class="row">
  <div class="col s6" width="200" style="width: 200px">
    <div width="200" style="width: 200px"><%= form_tag(locations_path, method: "get", id: "search-form") do %>
     <%= text_field_tag :search, params[:search], placeholder: "Search location or keyword" %>
      <%= submit_tag "Search", :name => nil %>
     <% end %></div>
     </div>

   <div class="col s6 offset-s1" width="200" style="width: 200px">
    <%= form_tag(locations_path, method: "get", id: "menu") do %>
      <select name = "option" class="browser-default" width="200" style="width: 200px">
        <option placeholder = "Sort">  Sort</option>
        <option value = "rating"> Sort by Rating</option>
        <option value = "neighborhood"> Sort by Neighborhood</option>
        <option value = "category"> Sort by Category</option>
      </select>
      <%= submit_tag 'submit' %>
    <% end %>
  </div>
</div>





<div class="row">
  <% @locations.each do |location| %>
    <div class="col s2 m4">
      <div class="card medium">
        <div class="card-image">
          <img src="<%= location.image_url %>" height="275" width="275">
          <span class="card-title"> <%= location.name %> </span>
        </div>
        <div class="card-content">
          <p> <%= location.stars %> <%= location.neighborhood %> <br><%= location.description.truncate(135, separator: ' ') %></p>
        </div>
        <div class="card-action">
          <%= link_to "More Info", location%>
        </div>
      </div>
    </div>
    <% end %>
  </div>



<br>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

  <h4>
  <%= @location.name %>
</h4>
<div class="row right">
  <div class="col s6" >
<img src ="<%=@location.image_url%>" height="450" width="550"></img>
</div>
</div>

<b>
  <strong>Overall Rating:</strong>
  <%= @location.overall_rating %>
</b>
<b>
  <strong>Neighborhood:</strong>
  <%= @location.neighborhood %>
</b>

<b>
  <%if @location.size%>
  <strong>Size:</strong>
  <%= @location.size %>
  <%end%>
</b>

<b>
  <strong>Cost of Admission:</strong>
  $<%= @location.cost_of_admission %>
</b>


<br><br>

<div class = "descript">
  <%= @location.description %>
</div>
<p>
  <b>Reviews:</b><br>
  <div class = "reviews" vlink="blue">
  <% @location.reviews.each do |review| %>
  <%= review.content %><br>
  <%= review.rating %> Stars
  -<%= link_to review.user.username, user_path(review.user.id) %><br><br>
<% end %>
<%= button_to "Leave Review", new_review_path, :method => :get,
  params: {location_id: @location.id}
%>

</div>
</p>
<br>
<p vlink="blue">
  <b>Events:</b><br>
  <ul>
  <% @location.events.each do |event| %>
  <%if event.start_date < DateTime.now && DateTime.now < event.end_date%>
  <li><%= link_to event.title, event_path(event.id)%> </li>
  <li><%= event.format_date(event.start_date) + " - " + event.format_date(event.end_date) %> </li>
  <li><%= event.days_left%> days left on view </li>
  <li><%= event.description %></li>
  <br>
<% end %>
<% end %>

</ul>
</p>
<p vlink="blue">
<b>Past Events:</b><br>
<ul>
<% @location.events.each do |event| %>
<% if event.end_date < DateTime.now %>
<li><%= link_to event.title, event_path(event.id)%> </li>
<li><%= event.format_date(event.start_date) + " - " + event.format_date(event.end_date) %> </li>
<li><%= event.description %></li><br>
<% end %>
<% end %>

</ul>
</p>




<%= link_to 'Back', locations_path %>