config/routes.rb
Rails.application.routes.draw do
  resources :event_users
  resources :location_types
  resources :locations, except: [:destroy]
  resources :events, except: [:destroy]
  resources :reviews, except: [:show]
  resources :users, except: [:index]
  get '/login', to: "sessions#new", as: 'login'
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/', to: "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XhibitApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="/app/stylesheets/application.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  </head>
<nav>
  <div class="nav-wrapper">
    <div class="brand-logo blue-text" font-color=""> &nbsp;Xhibit</div>
    <% if !!session[:user_id] %>
    <div class ="row abc">
    <ul id="nav-mobile" class="right">
       <li class = "nav-item"> <%= link_to "Profile", user_path(session[:user_id]) %></li>
        <li class = "nav-item"> <%= link_to "Locations", locations_path %></li>
        <li class = "nav-item"> <%= link_to "Events", events_path %></li>
        <li class = "nav-item"> <%= link_to "Log Out", logout_path %></li>
    </ul>
  </div>
  <% end %>
</nav>

  <body>
    <div class = "container2">
    <%= yield %>
    </div>
  </body>
</html>